#
# This is the environment specific properties file for PROD
#
http:
  host: "0.0.0.0"
  port: "8081"
  timeout: "30000"

devOps:
  appInsights:
    appender: "![5tUkMQWvTNlHFtnQ0qtKBw==]"
    
api:
  autoDiscoveryId: "19015484"